In [4]:
import h5py
with h5py.File('model\model2019_fullHead.h5', 'r') as f:
    f.visititems(lambda x, i:print(x, i))

catalog <HDF5 group "/catalog" (4 members)>
catalog/MorphableModel <HDF5 group "/catalog/MorphableModel" (2 members)>
catalog/MorphableModel/modelPath <HDF5 dataset "modelPath": shape (1,), type "|S1">
catalog/MorphableModel/modelType <HDF5 dataset "modelType": shape (1,), type "|S12">
catalog/MorphableModel.color <HDF5 group "/catalog/MorphableModel.color" (2 members)>
catalog/MorphableModel.color/modelPath <HDF5 dataset "modelPath": shape (1,), type "|S6">
catalog/MorphableModel.color/modelType <HDF5 dataset "modelType": shape (1,), type "|S23">
catalog/MorphableModel.expression <HDF5 group "/catalog/MorphableModel.expression" (2 members)>
catalog/MorphableModel.expression/modelPath <HDF5 dataset "modelPath": shape (1,), type "|S11">
catalog/MorphableModel.expression/modelType <HDF5 dataset "modelType": shape (1,), type "|S23">
catalog/MorphableModel.shape <HDF5 group "/catalog/MorphableModel.shape" (2 members)>
catalog/MorphableModel.shape/modelPath <HDF5 dataset "modelPath": shape 

In [6]:
import numpy as np
a = np.array([[1,1,1],[2,2,2]])
b = np.arange(3)
print(a)
print(b)
print(a@b)

[[1 1 1]
 [2 2 2]]
[0 1 2]
[3 6]


In [ ]:
# 打开摄像头并灰度化显示
import cv2
import dlib
import matplotlib.pyplot as plt
cap = cv2.VideoCapture(0) 
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("model/shape_predictor_68_face_landmarks.dat")
while(cap.isOpened()):
# 获取一帧
    ret, frame = cap.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = detector(gray, 1)
    for face in faces:

        # # 8.1 绘制矩形框
        # cv2.rectangle(frame, (face.left(), face.top()), (face.right(), face.bottom()), (0, 255, 0), 3)
        # 8.2 检测关键点
        shape = predictor(gray, face)
        #8.3 获取关键点坐标
        for pt in shape.parts():
            # 每个点的坐标
            pt_position = (pt.x, pt.y)
            # 绘制关键点
            cv2.circle(frame, pt_position, 3, (255, 0, 0), -1)

    cv2.imshow('frame', frame)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()