In [42]:
import h5py
import json
import numpy as np
import scipy
import pandas as pd
import scipy.io as sio
data = sio.loadmat('model\BFM.mat')['model']

In [51]:
print(data['shapeMU'][0, 0].T)
a = data['shapeMU'][0, 0].T.reshape(-1, 3)


[[-57239.016  42965.688  80410.125 ...  58620.625 -23110.14  -15202.358]]
[2. 3.]


In [69]:
a = np.array([[1,2],[2,3],[4,5]])
b = np.array([1,2])
print(a)
print(b)
print(a@b)

[[1 2]
 [2 3]
 [4 5]]
[1 2]
[ 5  8 14]


In [6]:
import numpy as np
a = np.array([[1,1,1],[2,2,2]])
b = np.arange(3)
print(a)
print(b)
print(a@b)

[[1 1 1]
 [2 2 2]]
[0 1 2]
[3 6]


In [ ]:
# 打开摄像头并灰度化显示
import cv2
import dlib
import matplotlib.pyplot as plt
cap = cv2.VideoCapture(0) 
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("model/shape_predictor_68_face_landmarks.dat")
while(cap.isOpened()):
# 获取一帧
    ret, frame = cap.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = detector(gray, 1)
    for face in faces:

        # # 8.1 绘制矩形框
        # cv2.rectangle(frame, (face.left(), face.top()), (face.right(), face.bottom()), (0, 255, 0), 3)
        # 8.2 检测关键点
        shape = predictor(gray, face)
        #8.3 获取关键点坐标
        for pt in shape.parts():
            # 每个点的坐标
            pt_position = (pt.x, pt.y)
            # 绘制关键点
            cv2.circle(frame, pt_position, 3, (255, 0, 0), -1)

    cv2.imshow('frame', frame)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()