In [42]:
import h5py
import json
import numpy as np
import scipy
import pandas as pd
import scipy.io as sio
data = sio.loadmat('model\BFM.mat')['model']

In [120]:
print(data['shapeEV'][0, 0].shape)

(199, 1)


In [5]:
import numpy as np
a = np.arange(10).reshape(-1,2)
b = a.mean(0)
print(a)
print(np.linalg.norm(a, ord = 1, axis=1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[ 1.  5.  9. 13. 17.]


In [2]:
import numpy as np
import cv2
img = cv2.imread('data/face1.jpg')
print(img)
print(img.flatten().dtype)

[[[40 52 45]
  [32 41 39]
  [30 40 36]
  ...
  [ 8 13  6]
  [18 23 15]
  [33 39 35]]

 [[30 42 39]
  [25 34 34]
  [26 36 34]
  ...
  [ 4  8  8]
  [ 9 16 14]
  [25 30 27]]

 [[25 39 35]
  [23 32 34]
  [23 31 36]
  ...
  [ 4  7  7]
  [ 5 12 11]
  [12 21 16]]

 ...

 [[67 69 61]
  [61 57 57]
  [56 51 49]
  ...
  [ 3  6  8]
  [ 2  7  6]
  [ 6 12  9]]

 [[63 66 64]
  [61 58 59]
  [53 48 45]
  ...
  [ 2  5  6]
  [ 5  8  8]
  [10 14 15]]

 [[64 65 66]
  [58 59 59]
  [44 43 43]
  ...
  [ 2 11  6]
  [ 2 14  9]
  [ 6 18 16]]]
uint8


In [ ]:
import cv2
import matplotlib.pyplot as plt
import dlib
import matplotlib.pyplot as plt
import numpy as np
import sys
import time
from pathlib import Path
sys.path[0] = str(Path(sys.path[0]).parent)
from lib.MorphabelModel import MorphabelModel as Model
from lib.Renderer import Renderer
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("model/shape_predictor_68_face_landmarks.dat")
frame = cv2.imread('data/face3.jpg')
frame = cv2.resize(frame, None, fx=0.4, fy = 0.4)
gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
faces = detector(gray, 1)
for face in faces:
    # # 8.1 绘制矩形框
    # cv2.rectangle(frame, (face.left(), face.top()), (face.right(), face.bottom()), (0, 255, 0), 3)
    # 8.2 检测关键点
    shape = predictor(gray, face)
    m = Model('model\BFM.mat', 500)
    points = np.array([[p.x, p.y] for p in shape.parts()])
    m.fit(points)
    v, c = m.transform()
    indices = m.tri.flatten()
    scale = np.max(np.max(v, axis=0)-np.min(v, axis=0))
    v/=scale
    c[m.kptInd] = np.tile(np.linspace(0, 1, m.kptInd.shape[0]), 3).reshape(3, -1).T
    r = Renderer()
    r.SetModel(v, c, indices)
    r.show()
    #8.3 获取关键点坐标
    for pt in shape.parts():
        # 每个点的坐标
        pt_position = (pt.x, pt.y)
        # 绘制关键点
        cv2.circle(frame, pt_position, 3, (255, 0, 0), -1)
cv2.imshow('frame', frame)
cv2.waitKey()
cv2.destroyAllWindows()

In [123]:
# 打开摄像头并灰度化显示
import cv2
import dlib
import matplotlib.pyplot as plt
cap = cv2.VideoCapture(0) 
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("model/shape_predictor_68_face_landmarks.dat")
while(cap.isOpened()):
# 获取一帧
    ret, frame = cap.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = detector(gray, 1)
    for face in faces:

        # # 8.1 绘制矩形框
        # cv2.rectangle(frame, (face.left(), face.top()), (face.right(), face.bottom()), (0, 255, 0), 3)
        # 8.2 检测关键点
        shape = predictor(gray, face)
        print(np.array([[p.x, p.y] for p in shape.parts()]))
        break
        #8.3 获取关键点坐标
        for pt in shape.parts():
            # 每个点的坐标
            pt_position = (pt.x, pt.y)
            # 绘制关键点
            cv2.circle(frame, pt_position, 3, (255, 0, 0), -1)

    cv2.imshow('frame', frame)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[[315 185]
 [315 212]
 [317 239]
 [322 265]
 [332 289]
 [347 308]
 [365 324]
 [385 336]
 [408 340]
 [431 337]
 [451 325]
 [469 309]
 [484 290]
 [494 268]
 [500 243]
 [506 217]
 [507 190]
 [332 172]
 [345 162]
 [363 162]
 [381 168]
 [397 177]
 [426 178]
 [441 170]
 [460 165]
 [478 167]
 [490 178]
 [411 193]
 [411 211]
 [411 229]
 [411 247]
 [391 258]
 [400 262]
 [410 264]
 [419 262]
 [428 258]
 [353 185]
 [364 179]
 [378 180]
 [388 192]
 [376 194]
 [362 193]
 [435 194]
 [446 183]
 [460 183]
 [470 190]
 [461 198]
 [447 198]
 [381 289]
 [393 288]
 [403 286]
 [410 288]
 [416 286]
 [426 289]
 [438 292]
 [425 296]
 [416 297]
 [409 297]
 [401 296]
 [393 294]
 [387 290]
 [403 294]
 [410 295]
 [416 295]
 [432 292]
 [416 285]
 [409 285]
 [403 284]]
[[303 202]
 [305 228]
 [308 253]
 [313 277]
 [323 299]
 [339 318]
 [360 334]
 [382 347]
 [405 351]
 [427 347]
 [445 334]
 [462 318]
 [476 300]
 [485 278]
 [489 255]
 [492 231]
 [493 207]
 [323 195]
 [339 186]
 [358 185]
 [377 188]
 [394 193]
 [418 193